My Project: poseEstimate::feature Class Reference
poseEstimate::feature Class Reference
#include <featureDetect.h>
Public Member Functions
void orbFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > &keyPoints, cv::Mat &descriptor)
Detect image ORB feature.
void siftFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > &keyPoints, cv::Mat &descriptor)
Detect image SIFT feature.
void surfFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > &keyPoints, cv::Mat &descriptor)
Detect image SURF feature.
void fastFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > &keyPoints, cv::Mat &descriptor)
Detect image FAST feature.
void readParams (std::string cam_param)
Read camera parameters and program parameters.
void createBoard ()
Create ARTag board using arucoCornersX and arucoCornersY from [readParams] function.
bool arucoDetect (cv::Mat rgb_image, cv::Mat depth_image, std::vector< int > ids, std::vector< std::vector< cv::Point3f >> &corners, Eigen::Matrix4f &trans)
Detect aruco corners and estimate current artag board pose.
void featureMatch (cv::Mat &desc_1, cv::Mat &desc_2, std::vector< cv::DMatch > &matches)
Detect aruco corners and estimate current artag board pose.
Public Member Functions inherited from poseEstimate::pose
void poseEstimation (std::vector< cv::Point3f > &src_points, std::vector< cv::Point3f > &tag_points, Eigen::Matrix4f &trans)
Detect image FAST feature.
Member Function Documentation
bool poseEstimate::feature::arucoDetect (cv::Mat rgb_image, cv::Mat depth_image, std::vector< int > ids, std::vector< std::vector< cv::Point3f >> & corners, Eigen::Matrix4f & trans)
Detect aruco corners and estimate current artag board pose.
Parameters
[in] rgb_image current rgb image
[in] depth_image current depth image
[out] ids corners id number
[out] corners artag corners
[out] trans current artag board pose
References poseEstimate::pose::poseEstimation(), t, and trans.
Referenced by callback().
void poseEstimate::feature::createBoard ()
Create ARTag board using arucoCornersX and arucoCornersY from [readParams] function.
Referenced by main().
void poseEstimate::feature::fastFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > & keyPoints, cv::Mat & descriptor)
Detect image FAST feature.
Parameters
[in] rgb_image current rgb image
[out] keyPoints detect rgb key corner points
[out] descriptor the descriptor of corner points
void poseEstimate::feature::featureMatch (cv::Mat & desc_1, cv::Mat & desc_2, std::vector< cv::DMatch > & matches)
Detect aruco corners and estimate current artag board pose.
Parameters
[in] desc_1 current image descriptors
[in] desc_2 previous image descriptors
[out] matches feature match descriptors
void poseEstimate::feature::orbFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > & keyPoints, cv::Mat & descriptor)
Detect image ORB feature.
Parameters
[in] rgb_image current rgb image
[out] keyPoints detect rgb key corner points
[out] descriptor the descriptor of corner points
void poseEstimate::feature::readParams (std::string cam_param)
Read camera parameters and program parameters.
Referenced by main().
void poseEstimate::feature::siftFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > & keyPoints, cv::Mat & descriptor)
Detect image SIFT feature.
Parameters
[in] rgb_image current rgb image
[out] keyPoints detect rgb key corner points
[out] descriptor the descriptor of corner points
void poseEstimate::feature::surfFeatureDetect (cv::Mat rgb_image, std::vector< cv::KeyPoint > & keyPoints, cv::Mat & descriptor)
Detect image SURF feature.
Parameters
[in] rgb_image current rgb image
[out] keyPoints detect rgb key corner points
[out] descriptor the descriptor of corner points
The documentation for this class was generated from the following files:
include/featureDetect.h
src/featureDetect.cpp