My Project: Examples/RGB-D/seg_label.cpp File Reference
seg_label.cpp File Reference
#include <pcl/visualization/cloud_viewer.h>
#include <pcl/console/print.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/pcd_io.h>
#include <pcl/console/parse.h>
#include <pcl/registration/transforms.h>
#include <pcl/filters/passthrough.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/filters/statistical_outlier_removal.h>
#include <pcl/registration/icp.h>
#include <pcl/registration/sample_consensus_prerejective.h>
#include <opencv2/opencv.hpp>
#include <pcl/features/fpfh_omp.h>
#include <pcl/features/normal_3d_omp.h>
#include <pcl/filters/fast_bilateral.h>
#include <pcl/filters/bilateral.h>
#include <pcl/search/kdtree.h>
#include <pcl/search/flann_search.h>
#include <pcl/segmentation/supervoxel_clustering.h>
#include <pcl/surface/mls.h>
#include <pcl/features/normal_3d.h>
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <algorithm>
Macros
#define READ_TRANS(TRANS, NAME) {Eigen::Matrix4f tmp_trans; ifstream(NAME.c_str(), std::ifstream::in | ifstream::binary).read((char*)tmp_trans.data(), 4 * 4 * sizeof(float)); (TRANS) = tmp_trans;}
read frame pose from file
Typedefs
typedef PointXYZRGBL PointT
typedef
visualization::PointCloudColorHandlerCustom
< PointT > ColorHandlerT
Functions
Mat convert2Map (PointCloud< PointT >::Ptr cloud)
Convert point cloud to depth mat.
Mat convert2Map (PointCloud< PointXYZL >::Ptr cloud)
Convert point cloud to depth mat.
void convertLabledCloud2Vec (PointCloud< PointT >::Ptr cloud, vector< PointCloud< PointT >::Ptr > &cloud_vec)
Convert PointXYZL cloud to vector cloud, different vectord coresponding to different label.
void convertLabledCloud2Vec (PointCloud< PointXYZL >::Ptr cloud, vector< PointCloud< PointXYZL >::Ptr > &cloud_vec)
Convert PointXYZL cloud to vector cloud, different vectord coresponding to different label.
int computeOverlap (Mat src, vector< Mat > tag)
Compute overlap ratio between src mat and tag vector, and return the max ratio index.
void labelPointCloud (PointCloud< PointT >::Ptr &cloud_src, PointCloud< PointXYZL >::Ptr &cloud_tag)
void superVoxleSeg (PointCloud< PointT >::Ptr &cloud, PointCloud< PointXYZL >::Ptr &seg_cloud)
Supervoxel segmentation.
void cloudPassFilter (PointCloud< PointT >::Ptr &cloud)
Cloud filter.
void cloudRenderMat (PointCloud< PointT >::Ptr cloud, vector< vector< pair< double, int >>> &cloud_vec)
Convert cloud to different type dataset structure.
void cloudRenderMatch (PointCloud< PointT >::Ptr &cloud, vector< vector< pair< double, int >>> cloud_vec)
Convert cloud to different type dataset structure.
double getAngle3D (Eigen::Vector3f &v1, Eigen::Vector3f &v2, const bool in_degree)
Supervoxel segmentation.
int main (int argc, char **argv)
Variables
double fx = 558.341390
camera intrinsic
double fy = 558.387543
double cx = 314.763671
double cy = 240.992295
set< int > label_set
Macro Definition Documentation
#define READ_TRANS (TRANS, NAME) {Eigen::Matrix4f tmp_trans; ifstream(NAME.c_str(), std::ifstream::in | ifstream::binary).read((char*)tmp_trans.data(), 4 * 4 * sizeof(float)); (TRANS) = tmp_trans;}
read frame pose from file
Referenced by main().
Typedef Documentation
typedef visualization::PointCloudColorHandlerCustom<PointT> ColorHandlerT
typedef PointXYZRGBL PointT
Function Documentation
void cloudPassFilter (PointCloud< PointT >::Ptr & cloud)
Cloud filter.
Referenced by main().
void cloudRenderMat (PointCloud< PointT >::Ptr cloud, vector< vector< pair< double, int >>> & cloud_vec)
Convert cloud to different type dataset structure.
References cx, cy, fx, fy, and label_set.
Referenced by main().
void cloudRenderMatch (PointCloud< PointT >::Ptr & cloud, vector< vector< pair< double, int >>> cloud_vec)
Convert cloud to different type dataset structure.
References cx, cy, fx, and fy.
Referenced by main().
int computeOverlap (Mat src, vector< Mat > tag)
Compute overlap ratio between src mat and tag vector, and return the max ratio index.
Parameters
[in] src
[in] tag a list mask vector
Returns
max ratio index
Referenced by main().
Mat convert2Map (PointCloud< PointT >::Ptr cloud)
Convert point cloud to depth mat.
References cx, cy, fx, and fy.
Referenced by main().
Mat convert2Map (PointCloud< PointXYZL >::Ptr cloud)
Convert point cloud to depth mat.
References cx, cy, fx, and fy.
void convertLabledCloud2Vec (PointCloud< PointT >::Ptr cloud, vector< PointCloud< PointT >::Ptr > & cloud_vec)
Convert PointXYZL cloud to vector cloud, different vectord coresponding to different label.
Referenced by main().
void convertLabledCloud2Vec (PointCloud< PointXYZL >::Ptr cloud, vector< PointCloud< PointXYZL >::Ptr > & cloud_vec)
Convert PointXYZL cloud to vector cloud, different vectord coresponding to different label.
double getAngle3D (Eigen::Vector3f & v1, Eigen::Vector3f & v2, const bool in_degree)
Supervoxel segmentation.
Parameters
[in] v1 one normal
[in] v2 another normal
[in] in_degree result is degree or angle model
Returns
normals angle
void labelPointCloud (PointCloud< PointT >::Ptr & cloud_src, PointCloud< PointXYZL >::Ptr & cloud_tag)
References cx, cy, fx, and fy.
Referenced by main().
int main (int argc, char ** argv)
References cloudPassFilter(), cloudRenderMat(), cloudRenderMatch(), computeOverlap(), convert2Map(), convertLabledCloud2Vec(), label_set, labelPointCloud(), READ_TRANS, superVoxleSeg(), and trans.
void superVoxleSeg (PointCloud< PointT >::Ptr & cloud, PointCloud< PointXYZL >::Ptr & seg_cloud)
Supervoxel segmentation.
Parameters
[in] cloud you need to segment
[out] seg_cloud supervoxel segmentation result
supervoxel segmentation///
Referenced by main().
Variable Documentation
double cx = 314.763671
Referenced by cloudRenderMat(), cloudRenderMatch(), convert2Map(), and labelPointCloud().
double cy = 240.992295
Referenced by cloudRenderMat(), cloudRenderMatch(), convert2Map(), and labelPointCloud().
double fx = 558.341390
camera intrinsic
Referenced by cloudRenderMat(), cloudRenderMatch(), convert2Map(), and labelPointCloud().
double fy = 558.387543
Referenced by cloudRenderMat(), cloudRenderMatch(), convert2Map(), and labelPointCloud().
set<int> label_set
Referenced by cloudRenderMat(), and main().